export { default as GetStarted } from './GetStarted';
export { default as LoginPage } from './LoginPage';
export { default as RegisterPage } from './RegisterPage';
export { default as ResetPage } from './ResetPage';
export { default as MainPage } from './MainPage';
export { default as ChatPage } from './ChatPage';
export { default as ApiPage } from './ApiPage';
export { default as DocsPage } from './DocsPage';
export { default as AboutPage } from './AboutPage';